<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Course;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            ['name' => 'Administração', 'category' => 'Ciências Sociais'],
            ['name' => 'Administração Pública', 'category' => 'Ciências Sociais'],
            ['name' => 'Agroecologia', 'category' => 'Agronomia'],
            ['name' => 'Agronegócio', 'category' => 'Agronomia'],
            ['name' => 'Agronomia', 'category' => 'Agronomia'],
            ['name' => 'Análise de Sistemas', 'category' => 'Tecnologia'],
            ['name' => 'Antropologia', 'category' => 'Ciências Sociais'],
            ['name' => 'Arquitetura e Urbanismo', 'category' => 'Artes'],
            ['name' => 'Arquivologia', 'category' => 'Ciências Sociais'],
            ['name' => 'Artes', 'category' => 'Artes'],
            ['name' => 'Artes Cênicas', 'category' => 'Artes'],
            ['name' => 'Astronomia', 'category' => 'Ciências'],
            ['name' => 'Biblioteconomia', 'category' => 'Ciências Sociais'],
            ['name' => 'Biologia', 'category' => 'Ciências'],
            ['name' => 'Biomedicina', 'category' => 'Saúde'],
            ['name' => 'Bioquímica', 'category' => 'Ciências'],
            ['name' => 'Canto', 'category' => 'Artes'],
            ['name' => 'Cenografia', 'category' => 'Artes'],
            ['name' => 'Ciência da Computação', 'category' => 'Tecnologia'],
            ['name' => 'Ciências Biológicas', 'category' => 'Ciências'],
            ['name' => 'Ciências Contábeis', 'category' => 'Ciências Sociais'],
            ['name' => 'Ciências Econômicas', 'category' => 'Ciências Sociais'],
            ['name' => 'Ciências Sociais', 'category' => 'Ciências Sociais'],
            ['name' => 'Cinema e Audiovisual', 'category' => 'Artes'],
            ['name' => 'Composição e Regência', 'category' => 'Artes'],
            ['name' => 'Computação', 'category' => 'Tecnologia'],
            ['name' => 'Comunicação e Marketing', 'category' => 'Ciências Sociais'],
            ['name' => 'Comunicação Social', 'category' => 'Ciências Sociais'],
            ['name' => 'Desenho Industrial', 'category' => 'Artes'],
            ['name' => 'Design', 'category' => 'Artes'],
            ['name' => 'Design de Ambientes', 'category' => 'Artes'],
            ['name' => 'Design de Games', 'category' => 'Artes'],
            ['name' => 'Design de Interiores', 'category' => 'Artes'],
            ['name' => 'Design de Moda', 'category' => 'Artes'],
            ['name' => 'Design de Produto', 'category' => 'Artes'],
            ['name' => 'Design Digital', 'category' => 'Artes'],
            ['name' => 'Design Gráfico', 'category' => 'Artes'],
            ['name' => 'Direção', 'category' => 'Artes'],
            ['name' => 'Direito', 'category' => 'Ciências Sociais'],
            ['name' => 'Educação Física', 'category' => 'Saúde'],
            ['name' => 'Enfermagem', 'category' => 'Saúde'],
            ['name' => 'Engenharia Acústica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Aeroespacial', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Aeronáutica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Agrícola', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Agroindustrial', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Agronômica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Ambiental', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Automotiva', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Bioenergética', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Biomédica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Bioquímica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Biotecnológica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Cartográfica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Civil', 'category' => 'Engenharia'],
            ['name' => 'Engenharia da Computação', 'category' => 'Engenharia'],
            ['name' => 'Engenharia da Mobilidade', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Agrimensura', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Agronegócios', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Alimentos', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Aquicultura', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Automação', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Bioprocessos', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Biossistemas', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Biotecnologia', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Energia', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Gestão', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Informação', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Instrumentação, Automação e Robótica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Manufatura', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Materiais', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Minas', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Pesca', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Petróleo', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Produção', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Recursos Hídricos', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Saúde e Segurança', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Sistemas', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Software', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Telecomunicações', 'category' => 'Engenharia'],
            ['name' => 'Engenharia de Transporte e Logística', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Elétrica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Eletrônica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia em Sistemas Digitais', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Ferroviária e Metroviária', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Física', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Florestal', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Geológica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Hídrica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Industrial', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Mecânica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Mecatrônica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Metalúrgica', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Naval', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Química', 'category' => 'Engenharia'],
            ['name' => 'Engenharia Têxtil', 'category' => 'Engenharia'],
            ['name' => 'Estatística', 'category' => 'Ciências'],
            ['name' => 'Farmácia', 'category' => 'Saúde'],
            ['name' => 'Filosofia', 'category' => 'Ciências Sociais'],
            ['name' => 'Física', 'category' => 'Ciências'],
            ['name' => 'Fisioterapia', 'category' => 'Saúde'],
            ['name' => 'Fonoaudiologia', 'category' => 'Saúde'],
            ['name' => 'Geografia', 'category' => 'Ciências Sociais'],
            ['name' => 'Gestão Ambiental', 'category' => 'Ciências Sociais'],
            ['name' => 'Gestão de Pessoas', 'category' => 'Ciências Sociais'],
            ['name' => 'Gestão de Tecnologia da Informação', 'category' => 'Tecnologia'],
            ['name' => 'Gestão Financeira', 'category' => 'Ciências Sociais'],
            ['name' => 'Gestão Hospitalar', 'category' => 'Saúde'],
            ['name' => 'Gestão Logística', 'category' => 'Ciências Sociais'],
            ['name' => 'História', 'category' => 'Ciências Sociais'],
            ['name' => 'Hospitalidade', 'category' => 'Ciências Sociais'],
            ['name' => 'Jornalismo', 'category' => 'Ciências Sociais'],
            ['name' => 'Letras', 'category' => 'Ciências Sociais'],
            ['name' => 'Licenciatura em Ciências', 'category' => 'Ciências'],
            ['name' => 'Licenciatura em Matemática', 'category' => 'Ciências'],
            ['name' => 'Linguística', 'category' => 'Ciências Sociais'],
            ['name' => 'Marketing', 'category' => 'Ciências Sociais'],
            ['name' => 'Matemática', 'category' => 'Ciências'],
            ['name' => 'Medicina', 'category' => 'Saúde'],
            ['name' => 'Medicina Veterinária', 'category' => 'Saúde'],
            ['name' => 'Musicalização', 'category' => 'Artes'],
            ['name' => 'Nutrição', 'category' => 'Saúde'],
            ['name' => 'Odontologia', 'category' => 'Saúde'],
            ['name' => 'Pedagogia', 'category' => 'Ciências Sociais'],
            ['name' => 'Psicologia', 'category' => 'Ciências Sociais'],
            ['name' => 'Publicidade e Propaganda', 'category' => 'Ciências Sociais'],
            ['name' => 'Química', 'category' => 'Ciências'],
            ['name' => 'Relações Internacionais', 'category' => 'Ciências Sociais'],
            ['name' => 'Relações Públicas', 'category' => 'Ciências Sociais'],
            ['name' => 'Secretariado Executivo', 'category' => 'Ciências Sociais'],
            ['name' => 'Serviço Social', 'category' => 'Ciências Sociais'],
            ['name' => 'Sistemas de Informação', 'category' => 'Tecnologia'],
            ['name' => 'Sociologia', 'category' => 'Ciências Sociais'],
            ['name' => 'Teatro', 'category' => 'Artes'],
            ['name' => 'Turismo', 'category' => 'Ciências Sociais'],
            ['name' => 'Zootecnia', 'category' => 'Agronomia'],
        ];

        foreach ($courses as $course) {
            Course::create([
                'name' => $course['name'],
                'category' => $course['category'],
            ]);
        }
    }
}
